---
- name: Installing at Launch Filebeat
  hosts: webservers
  become: yes
  tasks:
  - name: Download filebeat .deb file
    command: curl -L -O curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

  - name: Install filebeat .deb
    command: sudo dpkg --force-confold -i filebeat-7.6.1-amd64.deb

  - name: Drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Enable and configure System Module
    command: filebeat modules enable system

  - name: Setup filebeat
    command: filebeat setup

  - name: Start filebeat service
    command: service filebeat start

  - name: Enable filebeat service
    systemd:
      name: filebeat
      enabled: yes